project:
  type: website
  output-dir: _site
  resources: 
    - "*.mp4"
    - "*.txt"
    - "*.csv"

format: fminxyz-html

execute:
  freeze: auto

filters:
  - fminxyz

website:
  navbar:
    left: 
        - program.md
        - homework.md 
        - projects.md
    title: false
    logo: logo.svg
    logo-alt: mipt25.fmin.xyz
    tools:
      - icon: github
        href: https://github.com/MerkulovDaniil/mipt25
      - icon: youtube
        href: https://www.youtube.com/@fmin
      - icon: telegram
        href: https://t.me/mipt25_fmin
      - icon: person-workspace
        href: https://classroom.google.com/c/ODEzNzgyMzk2MTY0
      - icon: table
        href: https://docs.google.com/spreadsheets/d/1sySWzjk8R3y486KxP5ckpcI8B4ETDiYToveAO8Gzrts
      - icon: gem
        href: https://fmin.xyz
  repo-url: https://github.com/MerkulovDaniil/mipt25
  repo-branch: main
  repo-actions: [edit]
  search: 
    location: navbar
    type: textbox
  twitter-card: true
  open-graph: true
  favicon: favicon.svg